permalink: /:year/:title/

collections:
  case-studies:
    output: true
    permalink: /:categories/:path
categories:
- business
- design
- marketing


jekyll-archives:
  enabled: true
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
